// <auto-generated />
using AreaOrenk.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AreaOrenk.Data.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    partial class UygulamaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AreaOrenk.Data.Slayt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ResimYolu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Slaytlar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Lezzetli çilekli cupcake",
                            Baslik = "Çilekli Cupcake",
                            ResimYolu = "cilekliCup.jpg",
                            Sira = 1
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Bol çikolatalı dondurma",
                            Baslik = "Çikolatalı Dondurma",
                            ResimYolu = "cikolataliDondurma.jpg",
                            Sira = 2
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Yumuşacık pancake",
                            Baslik = "Pancake",
                            ResimYolu = "pancake.jpg",
                            Sira = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
